[ui] add typography component
dmapper/startupjs pull request #21
Opened 2019-12-15 09:39 UTC by estatix

2019-12-17 18:52 UTC, cray0000 commented on packages/ui/components/Typography/index.js
> +export const Normal = generateTag('Text')
а где `Span`?
`Normal` по-идее и должен быть `Span`. Надо его переименовать

2019-12-17 18:57 UTC, cray0000 commented on packages/ui/components/Typography/index.js
> +export const Small = generateTag('Text')
И еще Normal, Description, Small все `generateTag('Text')`.
А эту опцию ты используешь дальше для модификатора стилей. То есть у них у всех модификатор `-Text`. Надо `generateTag` давать 2 опции тогда -- одну для нативного web тэга, а вторую для модификатора для стилей

2019-12-17 19:01 UTC, cray0000 commented
И еще по поводу использования веб-тегов напрямую.
Этого делать нельзя, потому что `react-native-web` на `Text` навешивает свой функционал необходимый, чтобы все вело себя одинаково что в react-native, что в вебе. И если мы вместо `Text` используем для текста что-то другое, то мы все поломаем.

К счастью, у `Text` на react-native-web есть возможность зафорсить конкретный вебовский `h1-h6` тэг. Это делается при помощи дополнительных пропсов:

{ accessibilityRole: 'heading', 'aria-level': '3' }

Вот для референса: https://github.com/necolas/react-native-web/commit/1b172319b9ea257830a82cb6800ad3e7a746190c

То есть, если мы находимся на вебе, то надо просто домердживать дополнительные пропсы в `Text` для h1-h6.

h1: 
{ accessibilityRole: 'heading', 'aria-level': '1' }

h2: 
{ accessibilityRole: 'heading', 'aria-level': '2' }

ну и ты понял как дальше :)

2019-12-18 12:05 UTC, estatix commented
@cray0000 окей, запомнил. Спасибо. Done

2019-12-18 19:03 UTC, cray0000 requested changes

2019-12-18 19:03 UTC, cray0000 commented on packages/ui/components/Headers/index.js
> +      const role = isWeb && ariaLevelNumber ? { accessibilityRole: 'heading', 'aria-level': tag.match(/\d+/).join() } : {}
ariaLabelNumber уже не нужен, раз ты из тега достаешь. Ну и в generateTag ты его и не передаешь кстати, значит оно вообще не работает ща.

И еще там где ты из тега достаешь не понятно почему `.join` делается. Как будто там массив из многих элементов. И вообще раз ты завязываешься на тег `h<цифра>`, то логичнее будет просто обрезать первый символ и получить цифру.

```
tag.replace(/^h/, '')
```

2019-12-18 19:12 UTC, estatix commented on packages/ui/components/Headers/index.js
> +      const role = isWeb && ariaLevelNumber ? { accessibilityRole: 'heading', 'aria-level': tag.match(/\d+/).join() } : {}
@cray0000 исправил

2019-12-18 21:33 UTC, cray0000 requested changes

2019-12-18 21:33 UTC, cray0000 commented on packages/ui/components/Span/index.js
> +  bord: propTypes.bool
bord

2019-12-18 21:33 UTC, cray0000 commented on packages/ui/components/Headers/index.js
> +  return observer(
PropTypes надо добавлять перед тем как return`ить, похожим образом как в `Span`

2019-12-19 08:13 UTC, estatix commented on packages/ui/components/Span/index.js
> +  bord: propTypes.bool
исправил

2019-12-19 08:13 UTC, estatix commented on packages/ui/components/Headers/index.js
> +  return observer(
done

2019-12-24 09:12 UTC, merged