[ui] add icon component
dmapper/startupjs pull request #31
Opened 2019-12-23 12:27 UTC by simonz-git

2019-12-23 14:06 UTC, pturchik requested changes

2019-12-23 14:06 UTC, pturchik commented on packages/ui/components/Icon/index.js
> +  )
используй pug

2019-12-23 14:06 UTC, pturchik commented on packages/ui/components/Icon/index.js
> +  height: PropTypes.oneOfType([PropTypes.number, PropTypes.string])
давай только числа использовать

2019-12-23 14:06 UTC, pturchik commented on packages/ui/components/Icon/index.js
> +  size: PropTypes.oneOfType([PropTypes.number, PropTypes.oneOf(Object.keys(SIZES))]),
зачем тебе тут ещё числа?

2019-12-23 14:28 UTC, simonz-git commented on packages/ui/components/Icon/index.js
> +  )
done

2019-12-23 14:29 UTC, simonz-git commented on packages/ui/components/Icon/index.js
> +  height: PropTypes.oneOfType([PropTypes.number, PropTypes.string])
done

2019-12-23 14:48 UTC, simonz-git commented on packages/ui/components/Icon/index.js
> +  size: PropTypes.oneOfType([PropTypes.number, PropTypes.oneOf(Object.keys(SIZES))]),
done

2019-12-24 22:13 UTC, pturchik approved these changes

2019-12-24 22:13 UTC, merged