[ui] button component
dmapper/startupjs pull request #32
Opened 2019-12-26 08:42 UTC by estatix

2019-12-27 19:44 UTC, pturchik requested changes

2019-12-27 19:44 UTC, pturchik commented on packages/ui/components/Button/index.js
> +  iconSize: PropTypes.oneOf('xs', 's', 'm', 'l', 'xl', 'xxl'),
['xs', ...]

2019-12-27 19:44 UTC, pturchik commented on packages/ui/components/Button/index.js
> +  size, // large, big
можно не комментить. из propTypes и так все видно будет

2019-12-27 19:44 UTC, pturchik commented on packages/ui/components/Button/index.js
> +      onPress=disabled ? undefined : onPress
```js
disabled=disabled
onPress=onPress
```

2019-12-27 19:44 UTC, pturchik commented on packages/ui/components/Button/index.styl
> +_shadow = 5px 2px 8px 0px rgba(0,0,0,0.1)
? зачем если Div имеет и так тени.

2019-12-27 19:44 UTC, pturchik commented on packages/ui/components/Button/index.styl
> +_noBackground = rgba(0,0,0, 0)
spaces

2019-12-27 19:44 UTC, pturchik commented on packages/ui/components/Button/index.js
> +      shadow=variant==='shadowed' && 'm'
spaces

2020-01-23 13:06 UTC, pturchik requested changes

2020-01-23 13:06 UTC, pturchik commented on packages/ui/components/Button/index.js
> +  level: 0,
тени у кнопки быть не может, только у shadowed 2 lvl если я правильно помню что Тимофей говорил

2020-01-23 13:06 UTC, pturchik commented on packages/ui/components/Button/index.js
> +  level: propTypes.oneOf(SHADOWS.map((item, index) => index)),
remove

2020-01-23 13:08 UTC, pturchik requested changes

2020-01-23 13:08 UTC, pturchik commented on packages/ui/components/Button/index.js
> +  const _level = variant === 'shadowed' ? 2 : level
const extraProps = {}

if (variant === 'shadowed') extraProps.level = 2

2020-01-23 13:19 UTC, pturchik requested changes

2020-01-23 13:19 UTC, pturchik commented on packages/ui/components/Button/index.js
> +      level=_level
remove

2020-01-24 16:10 UTC, pturchik requested changes

2020-01-24 16:10 UTC, pturchik commented on packages/ui/components/Button/index.js
> +  shape: propTypes.oneOf(['rouneded', 'circle', 'squared']),
`rounded` - ты скопипастил из скайпа с ошибкой)))

2020-01-24 16:10 UTC, pturchik commented on packages/ui/components/Button/index.js
> +  shape: propTypes.oneOf(['rouneded', 'circle', 'squared']),
как оно тогда работало если default у тебя rounded))

2020-01-24 16:10 UTC, pturchik commented on packages/ui/components/Button/index.js
> +  onPress: propTypes.func.isRequired
не забудь потом удалить, а то и допиши логику где нибудь в styleguid'е что если func && isRequired то прокидывать пустую

2020-01-24 16:10 UTC, pturchik commented on packages/ui/components/Button/index.js
>  import { observer } from 'startupjs'
observer вверх подними

2020-01-24 16:10 UTC, pturchik commented on packages/ui/components/Button/index.js
> +import propTypes from 'prop-types'
prop-types тоже вверх

2020-01-24 16:10 UTC, pturchik commented on packages/ui/components/Button/index.js
> +const VARIANTS = {
зачем тебе они тут в переменной ? пропиши их просто в propTypes

2020-01-24 16:10 UTC, pturchik commented on packages/ui/components/Button/index.js
> +            color=iconsColor
назови iconsColor

2020-01-24 19:10 UTC, tohellandback commented on packages/ui/components/Button/index.js
> +  shape: propTypes.oneOf(['rouneded', 'circle', 'squared']),
magic :) а на самом деле я просто не задал модификатор для rounded и дефолтный радиус лежал в руте

2020-01-24 19:10 UTC, tohellandback commented on packages/ui/components/Button/index.js
> +            color=iconsColor
?:)

2020-01-24 19:16 UTC, pturchik requested changes

2020-01-24 19:16 UTC, pturchik commented on packages/ui/components/Button/index.styl
> +    border-radius 0
по умолчанию же 0

2020-01-24 19:16 UTC, pturchik commented on packages/ui/components/Button/index.js
> +        View.rightIcon(styleName=[size, {['with-label']: !!label}])
ты можешь стили для иконок вынести в переменную

iconWrapperStyle

2020-01-27 20:39 UTC, pturchik approved these changes

2020-01-27 20:39 UTC, merged