[ui]: progress component
dmapper/startupjs pull request #41
Opened 2020-01-09 17:44 UTC by estatix

2020-01-10 09:57 UTC, pturchik requested changes

2020-01-10 09:57 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +        Div.line(style={width: value <= total ? currentProgress + '%' : '100%', backgroundColor: color})
юзай везде `View`, тут нет необходимости в `Div` и тянуть лишний функционал

2020-01-10 09:57 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +  unfilledColor: PropTypes.string,
зачем тебе это в js ? вынести в css. смори примеры в компонентах с конфигом

2020-01-10 09:57 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +  color: PropTypes.string,
аналогично

2020-01-10 09:57 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +  value: 1,
0

2020-01-10 09:57 UTC, pturchik commented on packages/ui/components/Progress/index.styl
> +  color $UI.colors.darkLight
все переменные нужно вынести в конфиг

2020-01-10 13:43 UTC, pturchik requested changes

2020-01-10 13:43 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +        View.line(style={width: value <= total ? currentProgress + '%' : '100%', backgroundColor: color})
давай `.line` назовём `.filler` и тогда можно будет переменную назвать `fillerBg` для бэкграунда, а unfilledColor переименовать в `bgColor`

2020-01-10 13:43 UTC, pturchik commented on packages/ui/components/Progress/index.styl
> +.title
пиши классы в том порядке в котором они в html пожалуйста)

2020-01-10 13:43 UTC, pturchik commented on packages/ui/components/Progress/index.styl
> +  border-radius 3u
overflow hidden

2020-01-10 13:43 UTC, pturchik commented on packages/ui/components/Progress/index.styl
> +  border-radius 3u
почему такой большой ? в дизайне 4

2020-01-10 13:43 UTC, pturchik commented on packages/ui/components/Progress/index.styl
> +  height 1u
в дизайне 4

2020-01-10 13:43 UTC, pturchik commented on packages/ui/components/Progress/index.styl
> +  border-radius 3u
в дизайне 4

2020-01-10 13:43 UTC, pturchik commented on packages/ui/components/Progress/index.styl
> +  height 1u
в дизайне 4

2020-01-10 13:43 UTC, pturchik commented on packages/ui/components/Progress/index.styl
> +  height 1u
и вынести в переменные локальные

2020-01-12 11:08 UTC, estatix commented on packages/ui/components/Progress/index.styl
> +  border-radius 3u
тогда текст лейбла скрывается

2020-01-13 13:28 UTC, pturchik requested changes

2020-01-13 13:28 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +      View.progress(style={backgroundColor: unfilledColor})
тебе не нужно прописать одни и те же параметры и в js и в css.
оставляй в css если этот пропс кроссплатформенный. это же это было какое-то определенное свойство тега то конечно же тогда надо использовать js

2020-01-13 13:28 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +  unfilledColor: config.bgColor,
remove

2020-01-13 13:28 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +  unfilledColor,
remove

2020-01-13 13:28 UTC, pturchik commented on packages/ui/components/Progress/config.js
> +  fillerBg: '#2962FF'
глянь на конфиг Span'а к примеру откуда там берутся цвета

2020-01-13 13:28 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +          Text.label= value < total ? label + ' - ' + currentProgress.toFixed() + '% ...' : 'Loading Complete!'
используй `Span(description variant='caption')`

2020-01-13 15:00 UTC, estatix commented
<img width="1046" alt="Снимок экрана 2020-01-13 в 17 58 26" src="https://user-images.githubusercontent.com/53337412/72265984-7e162f00-362e-11ea-8dc4-91e91bfe80a4.png">

2020-01-14 08:43 UTC, pturchik requested changes

2020-01-14 08:43 UTC, pturchik commented on packages/ui/components/Progress/config.js
> +    textColor: colors.mainText,
тебе не нужно это, Span и так имеет такой цвет текста

2020-01-14 08:43 UTC, pturchik commented on packages/ui/components/Progress/config.js
> +    fillerBg: colors.primary
цвет в дизайне другой

2020-01-14 08:43 UTC, pturchik commented on packages/ui/components/Progress/config.js
> +    fillerBg: colors.primary
убирай это все из конфига, и в css используй просто локальные переменные

```js
$fillterBg = $UI.colors.primary
```
и так же все остальное


то что можно сделать в css нужно делать в css, потом при создании стайлгайда мы подумаем как нам это сделать кастомизируемым через конфиг.

2020-01-14 08:43 UTC, pturchik commented on packages/ui/components/Progress/index.styl
> +  color $UI.Progress.textColor
ты удалил тайтл, стиль нужно тоже удалить

2020-01-14 09:04 UTC, estatix commented
<img width="1675" alt="Снимок экрана 2020-01-14 в 12 02 43" src="https://user-images.githubusercontent.com/53337412/72329517-efed8780-36c5-11ea-9a1a-c3eed5262672.png">

2020-01-14 09:24 UTC, pturchik requested changes

2020-01-14 09:24 UTC, pturchik commented on packages/ui/components/Progress/config.js
> +}
та удаляй его нафиг уже))

2020-01-14 09:24 UTC, pturchik commented on packages/ui/components/Progress/index.styl
> +
remove empty line

2020-01-14 09:24 UTC, pturchik commented on packages/ui/components/Progress/index.styl
> +_fillerColor = #24B47E
`$UI.colors.success`
посмотри файлики `config/pallete` и `config/generateColorsFromPalette`, да и в целом папку `config` как там все генерируется. все цвета что есть в дизайне уже занесены в pallete/colors. использовать нужно всегда `colors`. если ты в дизайне увидишь цвет которого нет в цветах ui, то надо выяснить у Тимофея почему так - может это ошибка дизайнера, а может это какая-то особенность единоразовая к примеру как с background'ом Layout'а

2020-01-14 09:24 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +  total: 100,
это все тоже не особо тут нужно. суть прогресса в том что 100% это конечная. меньше больше быть не может

2020-01-14 09:24 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +        View.filler(style={width: value <= total ? currentProgress + '%' : '100%'})
width: value

2020-01-14 09:24 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +          Span(description variant='caption')= value < total ? label + ' - ' + currentProgress.toFixed() + '% ...' : 'Loading Complete!'
Span(...)
  = label
  ' - '
  = value + value <= 100 ? '% ...' : 'Loading Complete'

2020-01-14 09:24 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +  total: 100,
и проверь что если value будет больше 100, чтобы ничего не вылазило - для этого тебе нужно overflow hidden дать будет .progress скорей всего.

2020-01-14 10:15 UTC, estatix commented on packages/ui/components/Progress/index.styl
> +_fillerColor = #24B47E
всё, вопрос отпал окончательно, благодарю)

2020-01-14 12:33 UTC, pturchik requested changes

2020-01-14 12:33 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +  disableLabel: PropTypes.bool
давай добавим `variant` вместо `disableLabel` со значением `compact`, и тогда у нас если вид не компактный мы показываем label || defaultLabel (который будет value + '%...' : 'Loading Complete')

2020-01-14 12:34 UTC, pturchik requested changes

2020-01-14 12:34 UTC, pturchik commented on packages/ui/components/Progress/index.js
> +  disableLabel: PropTypes.bool
и наверное в defaultProps label тебе не нужно закидывать потому что это по факту будет часть label'а а не вся конструкция с ? :

2020-01-14 13:17 UTC, estatix commented
<img width="1042" alt="Снимок экрана 2020-01-14 в 16 14 07" src="https://user-images.githubusercontent.com/53337412/72347480-618afd00-36e9-11ea-9f50-f9b522388ebb.png">
<img width="1034" alt="Снимок экрана 2020-01-14 в 16 14 16" src="https://user-images.githubusercontent.com/53337412/72347482-618afd00-36e9-11ea-99d4-1b9d926ff742.png">

2020-01-15 18:46 UTC, merged